import { createApp } from "vue";
import { createPinia } from "pinia";
import App from "./App.vue";
import router from "./router";
import "quasar/dist/quasar.css";
import { QuillEditor } from "@vueup/vue-quill";
import "@vueup/vue-quill/dist/vue-quill.snow.css";
const app = createApp(App);
app.use(createPinia());
app.use(router);
app.mount("#app");
app.component("QuillEditor", QuillEditor);
